apiVersion: v1
kind: Service
metadata:
  name: getlinked-mistral-7b-service
  namespace: getlinked
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8081
  selector:
    app: getlinked-mistral-7b