apiVersion: apps/v1
kind: Deployment
metadata:
  name: getlinked-mistral-7b
  namespace: getlinked
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getlinked-mistral-7b
  template:
    metadata:
      labels:
        app: getlinked-mistral-7b
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "--http_port=8081",
          "--backend=127.0.0.1:8080",
          "--service=SERVICE-NAME",
          "--rollout_strategy=managed",
        ]
        ports:
        - containerPort: 8081
      - name: getlinked-mistral-7b
        image: ghcr.io/huggingface/text-generation-inference:1.1.1
        resources:
          limits:
            nvidia.com/gpu: '1'
        ports:
        - name: server-port
          containerPort: 8080
        env:
        - name: MODEL_ID
          value: mistralai/Mistral-7B-Instruct-v0.1
        - name: NUM_SHARD
          value: "1"
        - name: PORT 
          value: "8080"
        - name: QUANTIZE
          value: bitsandbytes-nf4
        volumeMounts:
          - mountPath: /dev/shm
            name: dshm
          - mountPath: /data
            name: data
      volumes:
         - name: dshm
           emptyDir:
              medium: Memory
         - name: data
           hostPath:
            path: /mnt/stateful_partition/kube-ephemeral-ssd/mistral-data
      serviceAccountName: getlinked-ksa
      nodeSelector:
        cloud.google.com/gke-accelerator: nvidia-l4
        cloud.google.com/gke-ephemeral-storage-local-ssd: "true"
        iam.gke.io/gke-metadata-server-enabled: "true"            